[versions]
# libraries
junit = "6.0.2"
junit4 = "4.13.2" # Required by IntelliJ Platform test framework
mockk = "1.14.7"
opentest4j = "1.3.0"
kotlinxSerialization = "1.9.0"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.3.0"
kover = "0.9.4"
qodana = "2025.3.1"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" } # Runtime dependency for IntelliJ Platform test framework compatibility
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
